fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
        files: ^(shell/|sched/)  # Solo chequea shell y sched
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
        files: ^(shell/|sched/)
      - id: check-added-large-files
        files: ^(shell/|sched/)
