name: pre-commit
on:
  pull_request:
  push:
jobs:
  pre-commit-shell:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shell
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  pre-commit-sched:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sched
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
